version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "generate-thumbnail"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1owitcsqk9e9q"
s3_prefix = "generate-thumbnail"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
